SSIS/views/colleges/__init__.py
from flask import Blueprint

colleges = Blueprint('college', __name__)

from . import routes

SSIS/views/colleges/routes.py
from flask import Flask, render_template, url_for, redirect, request, flash
from SSIS import mysql
from . import colleges

@colleges.route('/college')
def college():
    cur = mysql.connection.cursor()
    cur.execute("SELECT * FROM college_list")
    data = cur.fetchall()
    cur.close()

    return render_template('college.html', college_list = data)

@colleges.route('/add_college', methods = ['POST'])
def add_college():
    if request.method == "POST":
        flash("Data Inserted Successfully")
    if request.method == "POST":
        college_code = request.form['college_code']
        college_name = request.form['college_name']
        cur = mysql.connection.cursor()
        cur.execute("INSERT INTO college_list (college_code, college_name) VALUES (%s, %s)",
                        (college_code, college_name))
        mysql.connection.commit()
        return redirect(url_for('college.college'))

@colleges.route('/update_college', methods = ['POST', 'GET'])
def update_college():
    if request.method == 'POST':
        college_code = request.form['college_code']
        college_name = request.form['college_name']
        cur = mysql.connection.cursor()
        cur.execute(
            """UPDATE college_list SET college_name=%s WHERE college_code=%s""",
            (college_name, college_code))
        flash("Data updated successfully")
        mysql.connection.commit()
        return redirect(url_for('college.college'))

@colleges.route('/delete/college/<string:college_code>', methods = ['GET'])
def delete_college(college_code):
    flash("Record has been deleted successfully")
    cur = mysql.connection.cursor()
    cur.execute("DELETE FROM college_list WHERE college_code=%s", (college_code,))
    mysql.connection.commit()
    return redirect(url_for('college.college'))

@colleges.route('/searchcollege', methods=['GET', 'POST'])
def searchstudent():
    cur = mysql.connection.cursor()
    cur.execute("SELECT  * FROM college_list")
    colleges = cur.fetchall()
    user_input = request.form['tableSearch']
    keyword = user_input.upper()
    result = []

    for college in colleges:    
            student_allcaps = [str(info).upper() for info in college]
            if keyword in student_allcaps:
                result.append(college)
            result
   
    if not user_input:
        flash("Input All fields", "Error")

    if len(result) !=0:
        return render_template('college.html', college_list=result)
    else:
        return redirect(url_for('college.college'))

SSIS/templates/base.html
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>Student Information System</title>
    <link rel="shortcut icon" href="{{url_for('static', filename = 'stnd.jpg')}}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/main.css">

  </head>
  <body>
    {% include "navbar.html" %}
    <br/>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>




  </body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

SSIS/templates/college.html
{% extends "base.html" %}

    <link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
    <link rel="shortcut icon" href="{{url_for('static', filename = 'stnd.jpg')}}">

{% block content %}

<div class="container">

    <div class="well text-center">

        <h1>Welcome to Student Information System</h1>

    </div>

<div class="container">

    <div class="row">

        <div class="col md-12">

            <h2>College List <button type="button" class="btn btn-success pull-right" data-toggle="modal" data-target="#mymodal">
                Add College</button></h2>
            <form action="/searchcollege" method="post">
            <input class="form-control mb-4" id="tableSearch" name="tableSearch" type="text" placeholder="🔍 Search College.....">
            </form>
    {%with messages = get_flashed_messages()%}

    {%if messages%}

    {% for message in messages %}

    <div class="alert alert-success alert-dismissable" role="alert">

     <button type="button" class="close" data-dismiss="alert" aria-label ="close">

         <span aria-hidden="true">&times;</span>

     </button>
        {{message}}


    </div>

    {%endfor%}
    {%endif%}
    {%endwith%}

            <table class="table table-striped">

                <tr>
                    <th>Code</th>
                    <th>Name</th>
                    <th>Action</th>
                </tr>

                {% for row in college_list%}

                <tr>
                    <td>{{row.0}}</td>
                    <td>{{row.1}}</td>

                    <td>
                        <a href="/update/{{row.0}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{row.0}}">Edit</a>
                        <a href="/delete/college/{{row.0}}" class="btn btn-danger btn-xs" onclick="return confirm('Are you sure you want to delete?')">Delete</a>

                    </td>

                </tr>

                <div id="modaledit{{row.0}}" class="modal fade" role="dialog">

    <div class="modal-dialog">

       <div class="modal-content">

           <div class="modal-header">
            <h4 class="modal-title">Please Update Data</h4>
               <button type="button" class="close" data-dismiss="modal">&times</button>
               

           </div>

           <div class="modal-body">

               <form action="{{ url_for('college.update_college') }}" method="POST">

                   <div class="form-group">

                       <label>Code</label>
                       <input type="text" class="form-control" name="college_code" value="{{row.0}}">

                   </div>

                   <div class="form-group">

                       <label>Name</label>
                       <input type="text" class="form-control" name="college_name" value="{{row.1}}">

                   </div>

                   <div class="form-group">

                       <button class="btn btn-primary" type="submit">Update Data</button>

                   </div>


               </form>

           </div>

           <div class="modal-footer">

               <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

           </div>

       </div>

   </div>
</div>

                {% endfor %}


            </table>

        </div>


    <div id="mymodal" class="modal fade" role="dialog">
   <div class="modal-dialog">

       <div class="modal-content">

           <div class="modal-header">
            <h4 class="modal-title">Please Insert Data</h4>
               <button type="button" class="close" data-dismiss="modal">&times</button>
               

           </div>

           <div class="modal-body">

               <form action="{{url_for('college.add_college')}}" method="POST">

                   <div class="form-group">

                       <label>Code</label>
                       <input type="text" class="form-control" name="college_code" required="1">
                   </div>

                    <div class="form-group">

                        <label>Name</label>
                        <input type="text" class="form-control" name="college_name" required="1">
                    </div>

                   <div class="form-group">

                       <button class="btn btn-primary" type="submit">Insert Data</button>

                   </div>

               </form>

           </div>

           <div class="modal-footer">

               <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

           </div>

       </div>

   </div>

    </div>


</div>

</div>

</div>

{% endblock %}

<script type="text/javascript" src="{{url_for('static', filename='js/jquery-3.2.1.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>

SSIS/templates/course.html
{% extends "base.html" %}

    <link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
    <link rel="shortcut icon" href="{{url_for('static', filename = 'stnd.jpg')}}">

{% block content %}

<div class="container">

    <div class="well text-center">

        <h1>Welcome to Student Information System</h1>

    </div>

<div class="container">

    <div class="row">

        <div class="col md-12">

            <h2>Course List <button type="button" class="btn btn-success pull-right" data-toggle="modal" data-target="#mymodal">
                Add Course</button></h2>
            <form action="/searchcourse" method="post">
            <input class="form-control mb-4" id="tableSearch" name="tableSearch" type="text" placeholder="🔍 Search Course.....">
            </form>
    {%with messages = get_flashed_messages()%}

    {%if messages%}

    {% for message in messages %}

    <div class="alert alert-success alert-dismissable" role="alert">

     <button type="button" class="close" data-dismiss="alert" aria-label ="close">

         <span aria-hidden="true">&times;</span>

     </button>
        {{message}}


    </div>

    {%endfor%}
    {%endif%}
    {%endwith%}


            <table class="table table-striped">

                <tr>
                    <th>Code</th>
                    <th>Name</th>
                    <th>College</th>
                    <th>Action</th>
                </tr>

                {% for row in course_list%}

                <tr>
                    <td>{{row.0}}</td>
                    <td>{{row.1}}</td>
                    <td>{{row.2}}</td>

                    <td>
                        <a href="/update/{{row.0}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{row.0}}">Edit</a>
                        <a href="/delete/course/{{row.0}}" class="btn btn-danger btn-xs" onclick="return confirm('Are you sure you want to delete?')">Delete</a>

                    </td>

                </tr>

                <div id="modaledit{{row.0}}" class="modal fade" role="dialog">


   <div class="modal-dialog">

       <div class="modal-content">

           <div class="modal-header">
            <h4 class="modal-title">Please Update Data</h4>
               <button type="button" class="close" data-dismiss="modal">&times</button>
               

           </div>

           <div class="modal-body">

               <form action="{{ url_for('course.update_course') }}" method="POST">

                   <div class="form-group">

                       <label>Code</label>
                       <input type="text" class="form-control" name="course_code" value="{{row.0}}">

                   </div>

                    <div class="form-group">

                        <label>Name</label>
                        <input type="text" class="form-control" name="course_name" value="{{row.1}}">

                    </div>

                    <div class="form-group">
                        <label>College:</label> 
                        <div class="input-group mb-3" > 
                          <select class="custom-select" id="college" name="college" type="text" required>
                            <option selected="">Select a College</option>
                            {%for row in college%}
                            <option>{{row.0}}</option>
                            {%endfor%}
                          </select>
                        </div>
                      </div>

                   <div class="form-group">

                       <button class="btn btn-primary" type="submit">Update Data</button>

                   </div>


               </form>

           </div>

           <div class="modal-footer">

               <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

           </div>

       </div>

   </div>

</div>

                    {% endfor%}

                </tbody>

            </table>

        </div>


    <div id="mymodal" class="modal fade" role="dialog">
   <div class="modal-dialog">

       <div class="modal-content">

           <div class="modal-header">
            <h4 class="modal-title">Please Insert Data</h4>
               <button type="button" class="close" data-dismiss="modal">&times</button>
               

           </div>

           <div class="modal-body">

               <form action="{{url_for('course.add_course')}}" method="POST">

                   <div class="form-group">

                       <label>Code</label>
                       <input type="text" class="form-control" name="course_code" required="1">
                   </div>

                    <div class="form-group">

                        <label>Name</label>
                        <input type="text" class="form-control" name="course_name" required="1">
                    </div>

                    <div class="form-group">
                        <label>College:</label> 
                        <div class="input-group mb-3" > 
                          <select class="custom-select" id="college" name="college" type="text" required>
                            <option selected="">Select a College</option>
                            {%for row in college%}
                            <option>{{row.0}}</option>
                            {%endfor%}
                          </select>
                        </div>
                      </div>

                   <div class="form-group">

                       <button class="btn btn-primary" type="submit">Insert Data</button>

                   </div>

               </form>

           </div>

           <div class="modal-footer">

               <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

           </div>

       </div>

   </div>

    </div>


</div>

</div>

</div>

{% endblock %}

<script type="text/javascript" src="{{url_for('static', filename='js/jquery-3.2.1.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>

SSIS/templates/index.html
{% extends "base.html"%}
    <meta charset="UTF-8">
    <title>Student Information System</title>
    <link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
    <link rel="shortcut icon" href="{{url_for('static', filename = 'stnd.jpg')}}">
    
{%block content %}

<div class="container">

    <div class="well text-center">

        <h1>Welcome to Student Information System</h1>

    </div>

<div class="container">

    <div class="row">

        <div class="col md-12">

            <h2>Student List <button type="button" class="btn btn-success pull-right" data-toggle="modal" data-target="#mymodal">
                Add Student Data </button> </h2>
            <form action="/searchstudent" method="post">
            <input class="form-control mb-4" id="tableSearch" name="tableSearch" type="text" placeholder="🔍 Search Student.....">
            </form>
    {%with messages = get_flashed_messages()%}

    {%if messages%}

    {% for message in messages %}

    <div class="alert alert-success alert-dismissable" role="alert">

     <button type="button" class="close" data-dismiss="alert" aria-label ="close">

         <span aria-hidden="true">&times;</span>

     </button>
        {{message}}


    </div>

    {%endfor%}
    {%endif%}
    {%endwith%}


            <table class="table table-striped">

                <tr>
                    <th>#ID</th>
                    <th>Photo</th>
                    <th>Firstname</th>
                    <th>Lastname</th>
                    <th>Course</th>
                    <th>Year</th>
                    <th>Gender</th>
                    <th>Action</th>

                </tr>

                 {% for row in student_list %}
                <tr>
                    <td>{{row.0}}</td>
                    <td><img src="https://res.cloudinary.com/dmz5mj3xg/image/upload/v1643119194/ssis/{{row.0}}.jpg"></td>
                    <td>{{row.1}}</td>
                    <td>{{row.2}}</td>
                    <td>{{row.3}}</td>
					<td>{{row.4}}</td>
					<td>{{row.5}}</td>
                    <td>


               <a href="/update/{{row.0}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{row.0}}">Edit</a>
                <a href="/delete/student/{{ row.0 }}" class="btn btn-danger btn-xs" onclick="return confirm('Are You Sure For Delete?')">Delete</a>

                    </td>

                </tr>

                <div id="modaledit{{row.0}}" class="modal fade" role="dialog">


   <div class="modal-dialog">


      <div class="modal-content">


         <div class="modal-header">
            <h4 class="modal-title">Update Information</h4>

            <button type="button" class="close" data-dismiss="modal">&times;</button>




         </div>


         <div class="modal-body">


            <form action="{{ url_for('student.update') }}" method="POST"  enctype="multipart/form-data">


               <div class="form-group">


                  <label>ID:</label>
                  <input type="tel" placeholder="e.g. 0000-0000"  required class="form-control" name="stud_id"  value="{{row.0}} ">


               </div> 

               <div class="form-group" >
                <label>Photo:</label>
                <input class="form-control" type="file" name="file" id="formFile">  
                </div>

               <div class="form-group">


                  <label>Firstname:</label>
                  <input type="text" class="form-control" name="fname" value="{{row.1}}">


               </div>


               <div class="form-group">


                  <label>Lastname:</label>
                  <input type="text" class="form-control" name="lname" value="{{row.2}}">


               </div>

			   <div class="form-group">
                <label>Course:</label> 
                <div class="input-group mb-3" > 
                  <select class="custom-select" id="course" name="course" type="text" required>
                    <option selected="">Select a Course</option>
                    {%for row in course%}
                    <option value="{{row.0}}">{{row.0}}</option>
                    {%endfor%}
                  </select>
                </div>
              </div>

			   <div class="form-group">


                  <label>Year:</label>
                  <input type="text" class="form-control" name="year_lvl" value="{{row.4}}">


               </div>

			   <div class="form-group">


                  <label>Gender:</label>
                  <input type="text" class="form-control" name="gender" value="{{row.5}}">


               </div>


               <div class="form-group">


                  <button class="btn btn-primary" type="submit">Update</button>


               </div>


            </form>


         </div>


         <div class="modal-footer">


            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>


         </div>


      </div>


   </div>


</div>


                {% endfor  %}


                </tbody>


            </table>


        </div>

    <div id="mymodal" class="modal fade" role="dialog">
   <div class="modal-dialog">

       <div class="modal-content">

           <div class="modal-header">
            <h4 class="modal-title">Please Insert Data</h4>
               <button type="button" class="close" data-dismiss="modal">&times</button>
               
           </div>

           <div class="modal-body">

               <form action="{{url_for('student.insert')}}" enctype="multipart/form-data" method="POST">

                   <div class="form-group">

                       <label>#ID</label>
                       <input type="text" class="form-control" name="stud_id" required="1">

                   </div>

                   <div class="form-group" >
                    <label>Photo:</label>
                    <input class="form-control" type="file" name="file" id="formFile">  
                    </div>

                    <div class="form-group">

                        <label>Firstname</label>
                        <input type="text" class="form-control" name="fname" required="1">

                    </div>

                   <div class="form-group">

                       <label>Lastname</label>
                       <input type="text" class="form-control" name="lname" required="1">

                   </div>

                   <div class="form-group">
                    <label>Course:</label> 
                    <div class="input-group mb-3" > 
                      <select class="custom-select" id="course" name="course" type="text" required>
                        <option selected="">Select a Course</option>
                        {%for row in course%}
                        <option value="{{row.0}}">{{row.0}}</option>
                        {%endfor%}
                      </select>
                    </div>
                  </div>

                   <div class="form-group">

                       <label>Year</label>
                       <input type="text" class="form-control" name="year_lvl" required="1">

                   </div>

                   <div class="form-group">

                       <label>Gender</label>
                       <input type="text" class="form-control" name="gender" required="1">

                   </div>

                   <div class="form-group">

                       <button class="btn btn-primary" type="submit">Insert Data</button>

                   </div>

               </form>

           </div>

           <div class="modal-footer">

               <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

           </div>

       </div>


   </div>



    </div>



</div>


</div>
</div>

{% endblock %}

SSIS/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{{url_for('student.Index')}}">SSIS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('student.Index')}}">Student</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('course.course')}}">Courses</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="{{url_for('college.college')}}">College</a>
      </li>
    </ul>

  </div>
</nav>